# Generated by Django 4.1.1 on 2022-09-22 12:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("pdfapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentpagedetail",
            name="document",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_page_views",
                to="pdfapp.document",
            ),
        ),
        migrations.AlterField(
            model_name="documentpagedetail",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
