# Generated by Django 4.1.1 on 2022-09-22 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pdfapp", "0004_remove_document_views"),
    ]

    operations = [
        migrations.RemoveField(model_name="guestvisit", name="document",),
        migrations.AddField(
            model_name="guestvisit",
            name="doc_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_view",
                to="pdfapp.document",
            ),
        ),
    ]
