# Generated by Django 4.1.1 on 2022-09-23 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pdfapp", "0007_user"),
    ]

    operations = [
        migrations.DeleteModel(name="User",),
    ]
