# Generated by Django 4.1.1 on 2022-09-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pdfapp", "0009_account"),
    ]

    operations = [
        migrations.RemoveField(model_name="account", name="updated_at",),
    ]
