# Generated by Django 4.1.1 on 2022-09-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdfapp", "0011_account_company_account_total_login_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="total_document",
            field=models.IntegerField(default=0),
        ),
    ]
