# Generated by Django 4.1.1 on 2022-09-23 12:29

from django.db import migrations, models
import pdfapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ("pdfapp", "0012_account_total_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document",
            field=models.FileField(
                blank=True,
                default="",
                upload_to="",
                validators=[pdfapp.validators.validate_file_extension],
            ),
        ),
    ]
